[package]
name = "rapidus"
version = "0.1.0"
authors = ["maekawatoshiki <konndennsa@gmail.com>"]

[dependencies]
clap = "*"
bitflags = "*"
libc = "0.2"

[profile.dev]
codegen-units = 16

[profile.release]
codegen-units = 16
opt-level = 3
debug = false
lto = true
debug-assertions = false
panic = "unwind"
